apiVersion: v1
kind: Pod
metadata:
  name: l8-app-pod
spec:

  restartPolicy: Never
  
  containers:
    - name: l8-app-container
      image: thearyanahmed/l8-app:1.0
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "800m"
