version: '3.8'

#Docker Networks
networks:
  lk8s:
    driver: bridge

# Workflow
services:
  nginx_1:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./source:/var/www/html:delegated
    depends_on:
      - php
    networks:
      - lk8s

  # php:
  #   build:
  #     context: .
  #     dockerfile: ./compose/php/Dockerfile
  #   container_name: php
  #   volumes:
  #     - ./source:/var/www/html:delegated
  #     # Enable xdebug
  #     - ./compose/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  #   ports:
  #     - "9000:9000"
  #   networks:
  #     - lk8s